#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi
TOTAL_STAGES=0
_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()
_clear() { [[ -t 1 ]] || return 0; if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi; }
banner() { _clear; printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"; printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"; printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"; printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'; printf '  later — it remembers values already saved.%s\n' "$RESET"; pause "Ready to start?"; }
stage() { _clear; _STAGE_INDEX=$((_STAGE_INDEX + 1)); printf '\n%s%s▸ Stage %s/%s · %s%s\n' "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"; }
say() { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }
open_url() { local url="$1"; printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"; { if command -v wslview >/dev/null 2>&1; then wslview "$url"; elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"; elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$url"; elif command -v open >/dev/null 2>&1; then open "$url"; else warn "could not open a browser — visit it manually: $url"; fi; } >/dev/null 2>&1 || warn "could not open a browser — visit it manually: $url"; }
pause() { printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"; read -r _ || true; }
confirm() { local reply=""; printf '  %s? %s [y/N] ' "$YELLOW" "$1"; read -r reply || true; [[ "$reply" =~ ^[Yy] ]]; }
_existing() { [[ -f "$ENV_FILE" ]] || return 1; local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1; printf '%s' "${line#*=}"; }
ask() { local key="$1" prompt="$2" current input; current=$(_existing "$key" || true); if [[ -n "$current" ]]; then printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"; else printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"; fi; read -r input || true; [[ -z "$input" && -n "$current" ]] && input="$current"; printf -v "$key" '%s' "$input"; }
ask_secret() { local key="$1" prompt="$2" current input; current=$(_existing "$key" || true); if [[ -n "$current" ]]; then printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"; else printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"; fi; read -rs input || true; printf '\n'; [[ -z "$input" && -n "$current" ]] && input="$current"; printf -v "$key" '%s' "$input"; }
write_env() { local key="$1" value="$2" tmp; touch "$ENV_FILE"; tmp=$(mktemp); grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true; printf '%s=%s\n' "$key" "$value" >> "$tmp"; mv "$tmp" "$ENV_FILE"; WRITTEN_ENV+=("$key"); printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"; }
set_secret() { local name="$1" value="$2"; if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then if printf '%s' "$value" | gh secret set "$name" --repo dundunts/wage-app-web >/dev/null 2>&1; then WRITTEN_SECRET+=("$name"); printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"; return; fi; fi; SKIPPED+=("GitHub secret $name"); warn "skipped GitHub secret $name — gh not ready"; }
set_var() { local name="$1" value="$2"; if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then if gh variable set "$name" --repo dundunts/wage-app-web --body "$value" >/dev/null 2>&1; then printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"; return; fi; fi; SKIPPED+=("GitHub variable $name"); warn "skipped GitHub variable $name"; }
finish() { _clear; printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"; (( ${#WRITTEN_ENV[@]} )) && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"; (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"; if (( ${#SKIPPED[@]} )); then printf '\n'; warn "still to do by hand:"; for s in "${SKIPPED[@]}"; do note "  - $s"; done; fi; printf '\n'; }

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3
banner "Wage App web immutable release setup"

stage "Create the public Docker Hub repository"
open_url "https://hub.docker.com/repository/create"
step "Choose namespace dundunts and repository name wage-app-web."
step "Set visibility to Public. Do not create or push a tag by hand."
confirm "Does https://hub.docker.com/r/dundunts/wage-app-web now exist?" || { warn "Create the repository before continuing"; exit 1; }

stage "Store Docker Hub publication credentials"
open_url "https://app.docker.com/settings/personal-access-tokens"
step "Create a Personal Access Token with Read & Write scope."
step "Do not paste the token into chat, a command line, or a file."
ask DOCKER_USERNAME "Docker Hub username (must be dundunts):"
[[ "$DOCKER_USERNAME" == dundunts ]] || { warn "Only the canonical dundunts namespace is allowed"; exit 1; }
ask_secret DOCKER_PASSWORD "Paste the Read & Write token (input is hidden):"
[[ -n "$DOCKER_PASSWORD" ]] || { warn "Docker Hub token is required"; exit 1; }
set_secret DOCKER_USERNAME "$DOCKER_USERNAME"
set_secret DOCKER_PASSWORD "$DOCKER_PASSWORD"
unset DOCKER_PASSWORD

stage "Authorize the existing infrastructure promoter"
open_url "https://github.com/settings/apps/wage-app-release-promoter"
step "Confirm the app remains installed only on wage-app-infr with Contents and Pull requests Read & write."
ask INFRA_APP_ID "Paste the numeric App ID (not Client ID):"
[[ "$INFRA_APP_ID" =~ ^[0-9]+$ ]] || { warn "App ID must be numeric"; exit 1; }
step "Generate and download a new private key. Paste only its local file path below."
ask PRIVATE_KEY_PATH "Absolute path to the downloaded PEM file:"
[[ -f "$PRIVATE_KEY_PATH" && ! -L "$PRIVATE_KEY_PATH" ]] || { warn "Private key must be an existing regular file, not a symlink"; exit 1; }
private_key=$(<"$PRIVATE_KEY_PATH")
[[ "$private_key" == *"BEGIN RSA PRIVATE KEY"* || "$private_key" == *"BEGIN PRIVATE KEY"* ]] || { warn "File is not a PEM private key"; exit 1; }
set_secret INFRA_APP_ID "$INFRA_APP_ID"
set_secret INFRA_APP_PRIVATE_KEY "$private_key"
unset private_key

finish
